# MIT License
# Copyright (c) 2018 Gökhan Koçak
# www.gokhankocak.com

version: '2.2'

volumes:
  orderer.asena.fab:
  peer.asena.fab:
  cli.asena.fab:
  couchdb.asena.fab:

networks:
  fabric:

services:

  orderer.asena.fab:
    container_name: orderer.asena.fab
    image: hyperledger/fabric-orderer:1.2.0
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - ORDERER_GENERAL_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./artifacts/genesis.block:/var/hyperledger/fabric/genesis.block
    - ./crypto/ordererOrganizations/asena.fab/orderers/orderer.asena.fab/msp:/etc/hyperledger/fabric/msp
    - ./crypto/ordererOrganizations/asena.fab/orderers/orderer.asena.fab/tls/:/etc/hyperledger/fabric/tls
    - ./config/orderer/orderer.asena.fab/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    - ./data/orderer/orderer.asena.fab:/var/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - fabric

  peer.asena.fab:
    image: hyperledger/fabric-peer:1.2.0
    container_name: peer.asena.fab
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      #- CORE_PEER_ID=peer.asena.fab
      #- CORE_PEER_ADDRESS=peer.asena.fab:7051
      #- CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_LOCALMSPDIR=/etc/hyperledger/fabric/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
      #- CORE_PEER_TLS_ENABLED=true
      #- CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_GOSSIP_ORGLEADER=false
      #- CORE_PEER_PROFILE_ENABLED=false
      #- CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/asena.fab/users/Admin@asena.fab/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.asena.fab:5984
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /etc/hyperledger/fabric
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peerOrganizations/asena.fab/peers/peer.asena.fab/msp:/etc/hyperledger/fabric/msp
        - ./crypto/peerOrganizations/asena.fab/peers/peer.asena.fab/tls:/etc/hyperledger/fabric/tls
        - ./config/peers/peer.asena.fab/core.yaml:/etc/hyperledger/fabric/core.yaml
        - ./data/peers/peer.asena.fab:/var/hyperledger/fabric
        - ./crypto:/etc/hyperledger/fabric/crypto
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - fabric
    depends_on:
      - orderer.asena.fab
      - couchdb.asena.fab

  cli.asena.fab:
    container_name: cli.asena.fab
    image: hyperledger/fabric-tools:1.2.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
      - CORE_LOGGING_LEVEL=WARNING
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer.asena.fab:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/asena.fab/users/Admin@asena.fab/msp
      - ORDERER=orderer.asena.fab:7050
      - ORDERER_CA=/etc/hyperledger/fabric/peer/crypto/ordererOrganizations/asena.fab/orderers/orderer.asena.fab/msp/tlscacerts/tlsca.asena.fab-cert.pem
      - PEER_ORG1_CA=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/asena.fab/peers/peer.asena.fab/tls/ca.crt
    working_dir: /etc/hyperledger/fabric
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/etc/hyperledger/fabric/src/chaincode
        - ./crypto:/etc/hyperledger/fabric/crypto
        - ./scripts:/etc/hyperledger/fabric/scripts
        - ./artifacts:/etc/hyperledger/fabric/artifacts
        - ./crypto/peerOrganizations/asena.fab/peers/peer.asena.fab/msp:/etc/hyperledger/fabric/msp
        - ./crypto/peerOrganizations/asena.fab/peers/peer.asena.fab/tls:/etc/hyperledger/fabric/tls
        - ./config/peers/peer.asena.fab/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - fabric
    depends_on:
      - peer.asena.fab

  couchdb.asena.fab:
    container_name: couchdb.asena.fab
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - ./config/couchdb/couchdb.asena.fab/default.ini:/opt/couchdb/etc/default.ini
      - ./config/couchdb/couchdb.asena.fab/local.ini:/opt/couchdb/etc/local.ini
      - ./config/couchdb/couchdb.asena.fab/vm.args:/opt/couchdb/etc/vm.args
      - ./data/couchdb/couchdb.asena.fab:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      - fabric