# MIT License
# Copyright (c) 2018 Gökhan Koçak
# www.gokhankocak.com

version: '2.2'

volumes:
  orderer.asena.fabric:
  peer0.asena.fabric:
  couchdb0.asena.fabric:
  cli.asena.fabric:
  ca.asena.fabric:

networks:
  fabric:

services:

  orderer.asena.fabric:
    container_name: orderer.asena.fabric
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ORDERER_GENERAL_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - ORDERER_GENERAL_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./artifacts/genesis.block:/var/hyperledger/fabric/genesis.block
    - ./crypto/ordererOrganizations/asena.fabric/orderers/orderer.asena.fabric/msp:/etc/hyperledger/fabric/msp
    - ./crypto/ordererOrganizations/asena.fabric/orderers/orderer.asena.fabric/tls/:/etc/hyperledger/fabric/tls
    - ./config/orderer/orderer.asena.fabric/orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
    - ./data/orderer/orderer.asena.fabric:/var/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - fabric

  peer0.asena.fabric:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.asena.fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      #- CORE_PEER_ID=peer0.asena.fabric
      #- CORE_PEER_ADDRESS=peer0.asena.fabric:7051
      #- CORE_PEER_LOCALMSPID=Org1MSP
      #- CORE_PEER_LOCALMSPDIR=/etc/hyperledger/fabric/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
      #- CORE_PEER_TLS_ENABLED=true
      #- CORE_PEER_GOSSIP_USELEADERELECTION=true
      #- CORE_PEER_GOSSIP_ORGLEADER=false
      #- CORE_PEER_PROFILE_ENABLED=false
      #- CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      #- CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      #- CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/asena.fabric/users/Admin@asena.fabric/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.asena.fabric:5984
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      #- CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    working_dir: /etc/hyperledger/fabric
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto/peerOrganizations/asena.fabric/peers/peer0.asena.fabric/msp:/etc/hyperledger/fabric/msp
        - ./crypto/peerOrganizations/asena.fabric/peers/peer0.asena.fabric/tls:/etc/hyperledger/fabric/tls
        - ./config/peers/peer0.asena.fabric/core.yaml:/etc/hyperledger/fabric/core.yaml
        - ./data/peers/peer0.asena.fabric:/var/hyperledger/fabric
        - ./crypto:/etc/hyperledger/fabric/crypto
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - fabric
    depends_on:
      - orderer.asena.fabric
      - couchdb0.asena.fabric

  cli.asena.fabric:
    container_name: cli.asena.fabric
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=asena_fabric
      - CORE_LOGGING_LEVEL=WARNING
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.asena.fabric:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/crypto/peerOrganizations/asena.fabric/users/Admin@asena.fabric/msp
      - ORDERER=orderer.asena.fabric:7050
      - ORDERER_CA=/etc/hyperledger/fabric/peer/crypto/ordererOrganizations/asena.fabric/orderers/orderer.asena.fabric/msp/tlscacerts/tlsca.asena.fabric-cert.pem
      - PEER_ORG1_CA=/etc/hyperledger/fabric/peer/crypto/peerOrganizations/asena.fabric/peers/peer0.asena.fabric/tls/ca.crt
    working_dir: /etc/hyperledger/fabric
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/etc/hyperledger/fabric/src/chaincode
        - ./crypto:/etc/hyperledger/fabric/crypto
        - ./scripts:/etc/hyperledger/fabric/scripts
        - ./artifacts:/etc/hyperledger/fabric/artifacts
        - ./crypto/peerOrganizations/asena.fabric/peers/peer0.asena.fabric/msp:/etc/hyperledger/fabric/msp
        - ./crypto/peerOrganizations/asena.fabric/peers/peer0.asena.fabric/tls:/etc/hyperledger/fabric/tls
        - ./config/peers/peer0.asena.fabric/core.yaml:/etc/hyperledger/fabric/core.yaml
    networks:
      - fabric
    depends_on:
      - peer0.asena.fabric

  couchdb0.asena.fabric:
    container_name: couchdb0.asena.fabric
    image: hyperledger/fabric-couchdb:0.4.10
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    volumes:
      - ./config/couchdb/couchdb0.asena.fabric/default.ini:/opt/couchdb/etc/default.ini
      - ./config/couchdb/couchdb0.asena.fabric/local.ini:/opt/couchdb/etc/local.ini
      - ./config/couchdb/couchdb0.asena.fabric/vm.args:/opt/couchdb/etc/vm.args
      - ./data/couchdb/couchdb0.asena.fabric:/opt/couchdb/data
    ports:
      - 5984:5984
    networks:
      - fabric

  ca.asena.fabric:
    container_name: ca.asena.fabric
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-asena
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.asena.fabric-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/65c32c280a9ee8e18eb8b99aa4c9843b1637c548f6b43aeec675601e3d0534f3_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.asena.fabric-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/65c32c280a9ee8e18eb8b99aa4c9843b1637c548f6b43aeec675601e3d0534f3_sk -b admin:adminpw -d'
    volumes:
      - ./crypto/peerOrganizations/asena.fabric/ca:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric
